name: Upload Python Package

on:
  push:
    tags:
      - 'v*'  # v0.1.0, v1.2.3 এরকম ট্যাগে ট্রিগার হবে

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade build twine

      - name: Build package
        run: python -m build

      - name: Check package with Twine
        run: twine check dist/*

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
